#!/bin/sh
# install in /etc/pm/power.d/
# Go fast on AC power.  Similar to default Ubuntu settings
if on_ac_power; then

  # Remount ext filesystems 
  mount -o remount,commit=5,atime /

  # Disable SATA power saving
  for foo in /sys/class/scsi_host/host*/link_power_management_policy;
    do echo max_performance > $foo;
  done

  # Set the Intel wifi to no power savings.
  iw dev wlan0 set power_save off

  # Set kernel dirty page value back to default
  echo 10 > /proc/sys/vm/dirty_ratio
  echo 5 > /proc/sys/vm/dirty_background_ratio
  echo 600 > /proc/sys/vm/dirty_writeback_centisecs

  # turn off pci runtime powermanagement
  for pcidev in /sys/bus/pci/devices/0000\:0*/power/control
    do echo on > $pcidev
  done

  # enable the NMI watchdog
  echo 1 > /proc/sys/kernel/watchdog

  # disable autosuspend for a USB dev
  echo on > /sys/bus/usb/devices/1-3/power/control
  
  # mess with the intel HDMI audio
  echo '1' > '/sys/module/snd_hda_intel/parameters/power_save'

else # Save power, we are on battery
  # remount the file system to reduce journaling
  mount -o remount,commit=180,relatime /

  # SATA power saving
  for foo in /sys/class/scsi_host/host*/link_power_management_policy;
    do echo min_power > $foo;
  done

  # Set the Intel wifi to power savings.
  iw dev wlan0 set power_save on

  # Set kernel dirty page value to higher numbers
  echo 90 > /proc/sys/vm/dirty_ratio
  echo 1 > /proc/sys/vm/dirty_background_ratio
  echo 60000 > /proc/sys/vm/dirty_writeback_centisecs

  # turn on pci runtime powermanagement
  for pcidev in /sys/bus/pci/devices/0000\:0*/power/control
    do echo auto > $pcidev
  done

  # disable the NMI watchdog
  echo 0 > /proc/sys/kernel/watchdog

  # enable autosuspend for a USB dev
  echo auto > /sys/bus/usb/devices/1-3/power/control
  
  # mess with the intel HDMI audio
  echo '' > '/sys/module/snd_hda_intel/parameters/power_save'
fi

